name: 'OTLP Vulnerabilities Exporter'
description: 'Export vulnerability metrics over OTLP'
author: 'zgpcy'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  endpoint:
    description: The destination endpoint to export OpenTelemetry traces to
    required: true
  headers:
    description:
      Network Headers for the destination endpoint to export OpenTelemetry
      traces to
    required: false
  metricNamespace:
    description: The prefix to use for produced metrics
    required: true
  githubRepository:
    description: The github repository
    required: false
  serviceNameAttr:
    description: The resource.service attribute
    default: trivy-ci-action
    required: false
  serviceVersionAttr:
    description: The resource.version attribute
    default: 1.0.0
    required: false
  trivyOutputFile:
    description: The path to load trivy output
    required: true

runs:
  using: node20
  main: dist/index.js
